### ISSUE TITLE
Create new Gratipay stickers

### ISSUE THREAD

**Issue by rummik** [gratipay/inside.gratipay.com#137] opened 2015-01-28 21:34 UTC
I have a new laptop, and it needs stickers.  So I propose we solve this by having some new Gratipay stickers made up. :P

**Comment by whit537** [comment] 2015-01-28 22:05
cc: @LyndsySimon

**Comment by mattbk** [comment] 2016-02-21 17:04
+1

**Comment by lyndsysimon** [comment] 2016-03-31 19:38
Just say this. Do we just want another delivery to PyCon?

**Comment by whit537** [comment] 2016-03-31 19:49
!m @lyndsysimon 

I am not going to make it to PyCon this year, because it's too close to #314. Maybe @chrisdev and/or @citruspi will be there again (cf. #111)?

That said, the answer is: YES!!!!! It is time for more Gratipay stickers! :dancer:

**Comment by whit537** [comment] 2016-03-31 19:51
@lyndsysimon May I order a few hundred to hand out around Pittsburgh and in France (#534 #553 #556 #314)? What are your cost breakpoints?

**Comment by whit537** [comment] 2016-03-31 19:53
Going to PyCon 2016 reticketed as https://github.com/gratipay/inside.gratipay.com/issues/557.

**Comment by whit537** [comment] 2016-11-28 15:43
Bump. Should we use StickerMule for this, now that @jdorfman has landed there? Seems like a heartcoin sticker is a no-brainer. :)

**Comment by whit537** [comment] 2016-11-28 15:44
https://www.stickermule.com/products/circle-stickers

**Comment by mattbk** [comment] 2016-12-19 16:11
I approve sticker spending.

**Comment by jdorfman** [comment] 2016-12-20 18:19
@mattbk no spending needed, @whit537 knows who to contact.

**Comment by whit537** [comment] 2016-12-20 20:45
Hah! Thanks @jdorfman! 💃 

How do we proceed? Should we upload to StickerMule.com?

**Comment by jdorfman** [comment] 2016-12-20 21:14
@whit537 email jdorfman @ stickermule.com and I will get the process started. Not sure if you want your address and phone number on a GitHub issue.

**Comment by whit537** [comment] 2016-12-20 21:33
Mail sent! Thank you! 💃

> Not sure if you want your address and phone number on a GitHub issue.

Well they're on [my homepage](http://whit537.org/), so I don't see why not. ;-)

> my cell is +1-412-925-4220, and my address is 716 Park Road.

That's Ambridge, PA 15003.

**Comment by jdorfman** [comment] 2016-12-20 21:38
I forget how insanely transparent you are. =p

**Comment by whit537** [comment] 2016-12-20 21:46
Insanely transparent would be publishing our database password. :-P

> let me know the following:
>
>* Quantity of stickers
>* Sticker Type (Die cut, square, clear, etc)
>* Size (2x2, 2x3, etc)
>* Size examples: https://cl.ly/2r3y26360O0o

Love the picture!

![image 2016-12-07 at 8 49 28 am](https://cloud.githubusercontent.com/assets/134455/21369182/bd47c5d0-c6d3-11e6-8c21-4fa3078e8b64.png)

**Comment by jdorfman** [comment] 2016-12-20 21:49
> Insanely transparent would be publishing our database password. :-P

That is a true story

> Love the picture!

I dig it, puts things in perspective.

**Comment by whit537** [comment] 2016-12-20 22:00
I've created an account on Sticker Mule (and I've finally put our profile/banner pics on Inside Gratipay's [brand page](http://inside.gratipay.com/big-picture/brand); #945 ;).

**Comment by whit537** [comment] 2016-12-20 22:00
@jdorfman Do we get a public profile somewhere? https://www.stickermule.com/Gratipay

**Comment by whit537** [comment] 2016-12-20 22:01
Should we go for the roughly coin-sized 1" round stickers?

SVG is here: http://localhost:8536/assets/heart-coin.svg.

**Comment by jdorfman** [comment] 2016-12-20 22:02
What is the email on the account? That works, how many do you want to print?

**Comment by whit537** [comment] 2016-12-20 22:02
vendors@gratipay

**Comment by jdorfman** [comment] 2016-12-20 22:03
@whit537 How many do you want to print?

**Comment by jdorfman** [comment] 2016-12-20 22:04
Let's go with 300

**Comment by whit537** [comment] 2016-12-20 22:09
@jdorfman Deal! 👌

**Comment by jdorfman** [comment] 2016-12-20 22:09
| DATE ISSUED  |  AMOUNT |  EXPIRES ON |
|---|---|---|
|December 20, 2016   | $75  | March 20, 2017  |

**Comment by whit537** [comment] 2016-12-20 22:11
![screen shot 2016-12-20 at 5 10 31 pm](https://cloud.githubusercontent.com/assets/134455/21369913/3ecf5da4-c6d7-11e6-894e-8050c3fc74ad.png)

**Comment by whit537** [comment] 2016-12-20 22:11
![screen shot 2016-12-20 at 5 11 14 pm](https://cloud.githubusercontent.com/assets/134455/21369920/5466cf9e-c6d7-11e6-8526-6ebe9155a9bf.png)

**Comment by jdorfman** [comment] 2016-12-20 22:11
How it's done these days

**Comment by whit537** [comment] 2016-12-20 22:12
Mad thanks, @jdorfman! Can't wait to tweet/send these out! 💃

**Comment by jdorfman** [comment] 2016-12-20 22:13
That was fun, I want to do it again haha

**Comment by whit537** [comment] 2016-12-20 22:26
@jdorfman Look good for a tweet from @Gratipay?

![screen shot 2016-12-20 at 5 25 39 pm](https://cloud.githubusercontent.com/assets/134455/21370382/5fd34694-c6d9-11e6-8fbf-2422aa68f8d3.png)

**Comment by whit537** [comment] 2016-12-20 22:27
([personal thanks](https://twitter.com/whit537/status/811334255099801600))

**Comment by whit537** [comment] 2016-12-20 22:37
Confirmed in private Slack. [Published](https://twitter.com/Gratipay/status/811339260179652609)!

**Comment by whit537** [comment] 2016-12-20 22:39
Leaving open until these are in hand ...

**Comment by whit537** [comment] 2016-12-20 22:39
!m @jdorfman 
!m * 💃

**Comment by nashe** [comment] 2016-12-21 01:02
!m * 
Keep me one or two Gratipay stickers, I'll come at OuiShare too ;-)

**Comment by whit537** [comment] 2016-12-21 03:44
![screen shot 2016-12-20 at 10 43 45 pm](https://cloud.githubusercontent.com/assets/134455/21376775/d0db30be-c705-11e6-9507-7b5e2090fd2d.png)

**Comment by whit537** [comment] 2016-12-21 03:44
![screen shot 2016-12-20 at 10 44 25 pm](https://cloud.githubusercontent.com/assets/134455/21376787/e2f14f22-c705-11e6-810a-85d7e84ca4b7.png)

**Comment by jdorfman** [comment] 2016-12-21 16:00
@whit537 curious to know what `!m` does/means

**Comment by mattbk** [comment] 2016-12-21 16:10
It's a shortcut for "You're doing good work!" from the IRC channel. Also works in [Slack](https://gratipay.slack.com/messages).

**Comment by jdorfman** [comment] 2016-12-21 16:12
ah that makes sense.

Regards,

Justin Dorfman <http://www.justindorfman.com>
<http://www.justindorfman.com>
818.485.1458
@jdorfman <http://www.twitter.com/jdorfman>

**Comment by mattbk** [comment] 2016-12-21 16:14
Aha, knew this existed: http://motivate.im/

**Comment by whit537** [comment] 2016-12-22 18:06
Here tomorrow! 😱 

![screen shot 2016-12-22 at 1 04 30 pm](https://cloud.githubusercontent.com/assets/134455/21435327/41f3a460-c847-11e6-8ae9-83662306f2fb.png)

**Comment by jdorfman** [comment] 2016-12-22 20:30
Holy shit. Have you ordered before? That seems way too fast for a non-rush job.

**Comment by whit537** [comment] 2017-02-14 19:38
https://twitter.com/Gratipay/status/815938335462014977 💃

**Closed by whit537** 2017-02-14 19:38 UTC
Labels: Marketing

**Comment by martinheidegger** [comment] 2017-03-27 02:15
I created the workshopper org on NPM https://www.npmjs.com/org/workshopper/members and invited @workshopper/deploy to it.
