### ISSUE TITLE
Implement humans.txt

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#246] opened 2015-06-10 09:30 UTC
http://humanstxt.org/ - as a human, I want to know who did what when and all that stuff.. =)

**Comment by whit537** [comment] 2015-06-10 13:22
Duplicate of https://github.com/gratipay/gratipay.com/issues/661.

**Closed by whit537** 2015-06-10 13:22 UTC

**Comment by techtonik** [comment] 2015-06-11 15:12
Ok. I will revisit it later with a dump of active team members and honorary mentions. =)
