### ISSUE TITLE
So, how do we report spam?

### ISSUE THREAD

**Issue by techtonik** [gratipay/inside.gratipay.com#375] opened 2015-10-19 02:18 UTC
For example, https://gratipay.com/~jaklinbadr/

**Comment by mattbk** [comment] 2015-10-19 14:06
There's the [suspicious] flag, but I don't know what happens after that.

**Comment by techtonik** [comment] 2015-10-19 14:09
@mattbk I don't see where to set the flag in the new interface (which I like for its simplicity, BTW).

**Comment by mattbk** [comment] 2015-10-19 14:12
It's on the bottom of the ~user profle image for me when logged in as admin (or whatever status I have).

**Comment by techtonik** [comment] 2015-10-19 14:14
I don't see it, which means ordinary users can not report spam to us.

**Comment by mattbk** [comment] 2015-10-19 14:18
Yup, it doesn't make sense.

**Comment by rohitpaulk** [comment] 2015-10-19 14:44
Duplicate of https://github.com/gratipay/gratipay.com/issues/3060?

**Comment by techtonik** [comment] 2015-10-20 05:43
@rohitpaulk could be the dupe, but there should be some manual way also if the button does not work. I also don't like "report user" name.

**Comment by mattbk** [comment] 2015-10-22 14:00
This is the closest I've found: http://inside.gratipay.com/howto/handle-terms-violations, and the following are linked from there: https://github.com/gratipay/gratipay.com/issues/2992 and https://github.com/gratipay/gratipay.com/issues/3058.

**Comment by whit537** [comment] 2016-01-11 22:20
Closing as a dupe of https://github.com/gratipay/gratipay.com/issues/3060.

**Closed by whit537** 2016-01-11 22:20 UTC
